# Generated by Django 5.1.3 on 2024-11-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('biomedical equipment', 'biomedical equipment'), ('pharmacy', 'pharmacy'), ('lab', 'lab'), ('admin', 'admin')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
